# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "elastic-mapreduce"
  s.version = "2013.12.10"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Amazon.com", "Koichi Fujikawa"]
  s.date = "2014-04-25"
  s.description = "Original is official but this is Unofficial gem."
  s.email = "fujibee@hapyrus.com"
  s.executables = ["elastic-mapreduce"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README",
    "README.header"
  ]
  s.files = [
    ".gitmodules",
    "CHANGELOG",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "NOTICE.txt",
    "README",
    "README.header",
    "Rakefile",
    "VERSION",
    "bin/elastic-mapreduce",
    "ec2_roles.rb",
    "elastic-mapreduce.gemspec",
    "lib/amazon/aws/exceptions.rb",
    "lib/amazon/coral/awsquery.rb",
    "lib/amazon/coral/awsquerychainhelper.rb",
    "lib/amazon/coral/awsqueryhandler.rb",
    "lib/amazon/coral/awsqueryurihandler.rb",
    "lib/amazon/coral/call.rb",
    "lib/amazon/coral/dispatcher.rb",
    "lib/amazon/coral/ec2client.rb",
    "lib/amazon/coral/elasticmapreduceclient.rb",
    "lib/amazon/coral/handler.rb",
    "lib/amazon/coral/httpdelegationhelper.rb",
    "lib/amazon/coral/httpdestinationhandler.rb",
    "lib/amazon/coral/httphandler.rb",
    "lib/amazon/coral/identityhandler.rb",
    "lib/amazon/coral/job.rb",
    "lib/amazon/coral/logfactory.rb",
    "lib/amazon/coral/option.rb",
    "lib/amazon/coral/orchestrator.rb",
    "lib/amazon/coral/querystringmap.rb",
    "lib/amazon/coral/service.rb",
    "lib/amazon/coral/simplelog.rb",
    "lib/amazon/coral/urlencoding.rb",
    "lib/amazon/coral/v0signaturehandler.rb",
    "lib/amazon/coral/v0signaturehelper.rb",
    "lib/amazon/coral/v1signaturehandler.rb",
    "lib/amazon/coral/v1signaturehelper.rb",
    "lib/amazon/coral/v2signaturehandler.rb",
    "lib/amazon/coral/v2signaturehelper.rb",
    "lib/amazon/exceptions.rb",
    "lib/amazon/retry_delegator.rb",
    "lib/amazon/stderr_logger.rb",
    "lib/aws/api_config/IAM-2010-05-08.yml",
    "lib/aws/core.rb",
    "lib/aws/core/async_handle.rb",
    "lib/aws/core/autoloader.rb",
    "lib/aws/core/cacheable.rb",
    "lib/aws/core/client.rb",
    "lib/aws/core/collection.rb",
    "lib/aws/core/collection/simple.rb",
    "lib/aws/core/collection/with_limit_and_next_token.rb",
    "lib/aws/core/collection/with_next_token.rb",
    "lib/aws/core/configuration.rb",
    "lib/aws/core/credential_providers.rb",
    "lib/aws/core/data.rb",
    "lib/aws/core/http/curb_handler.rb",
    "lib/aws/core/http/handler.rb",
    "lib/aws/core/http/httparty_handler.rb",
    "lib/aws/core/http/net_http_handler.rb",
    "lib/aws/core/http/request.rb",
    "lib/aws/core/http/response.rb",
    "lib/aws/core/indifferent_hash.rb",
    "lib/aws/core/inflection.rb",
    "lib/aws/core/json_client.rb",
    "lib/aws/core/json_request_builder.rb",
    "lib/aws/core/json_response_parser.rb",
    "lib/aws/core/lazy_error_classes.rb",
    "lib/aws/core/log_formatter.rb",
    "lib/aws/core/meta_utils.rb",
    "lib/aws/core/model.rb",
    "lib/aws/core/naming.rb",
    "lib/aws/core/option_grammar.rb",
    "lib/aws/core/options/validator.rb",
    "lib/aws/core/options/xml_serializer.rb",
    "lib/aws/core/page_result.rb",
    "lib/aws/core/policy.rb",
    "lib/aws/core/query_client.rb",
    "lib/aws/core/query_error_parser.rb",
    "lib/aws/core/query_request_builder.rb",
    "lib/aws/core/query_response_parser.rb",
    "lib/aws/core/resource.rb",
    "lib/aws/core/resource_cache.rb",
    "lib/aws/core/response.rb",
    "lib/aws/core/response_cache.rb",
    "lib/aws/core/rest_client.rb",
    "lib/aws/core/rest_error_parser.rb",
    "lib/aws/core/rest_request_builder.rb",
    "lib/aws/core/rest_response_parser.rb",
    "lib/aws/core/service_interface.rb",
    "lib/aws/core/signature/version_2.rb",
    "lib/aws/core/signature/version_3.rb",
    "lib/aws/core/signature/version_3_https.rb",
    "lib/aws/core/signature/version_4.rb",
    "lib/aws/core/signer.rb",
    "lib/aws/core/uri_escape.rb",
    "lib/aws/core/xml/frame.rb",
    "lib/aws/core/xml/frame_stack.rb",
    "lib/aws/core/xml/grammar.rb",
    "lib/aws/core/xml/parser.rb",
    "lib/aws/core/xml/root_frame.rb",
    "lib/aws/core/xml/sax_handlers/libxml.rb",
    "lib/aws/core/xml/sax_handlers/nokogiri.rb",
    "lib/aws/core/xml/sax_handlers/ox.rb",
    "lib/aws/core/xml/sax_handlers/rexml.rb",
    "lib/aws/core/xml/stub.rb",
    "lib/aws/errors.rb",
    "lib/aws/iam.rb",
    "lib/aws/iam/access_key.rb",
    "lib/aws/iam/access_key_collection.rb",
    "lib/aws/iam/account_alias_collection.rb",
    "lib/aws/iam/client.rb",
    "lib/aws/iam/collection.rb",
    "lib/aws/iam/config.rb",
    "lib/aws/iam/errors.rb",
    "lib/aws/iam/group.rb",
    "lib/aws/iam/group_collection.rb",
    "lib/aws/iam/group_policy_collection.rb",
    "lib/aws/iam/group_user_collection.rb",
    "lib/aws/iam/login_profile.rb",
    "lib/aws/iam/mfa_device.rb",
    "lib/aws/iam/mfa_device_collection.rb",
    "lib/aws/iam/policy.rb",
    "lib/aws/iam/policy_collection.rb",
    "lib/aws/iam/request.rb",
    "lib/aws/iam/resource.rb",
    "lib/aws/iam/server_certificate.rb",
    "lib/aws/iam/server_certificate_collection.rb",
    "lib/aws/iam/signing_certificate.rb",
    "lib/aws/iam/signing_certificate_collection.rb",
    "lib/aws/iam/user.rb",
    "lib/aws/iam/user_collection.rb",
    "lib/aws/iam/user_group_collection.rb",
    "lib/aws/iam/user_policy.rb",
    "lib/aws/iam/user_policy_collection.rb",
    "lib/aws/iam/virtual_mfa_device.rb",
    "lib/aws/iam/virtual_mfa_device_collection.rb",
    "lib/aws/version.rb",
    "lib/cacert.pem",
    "lib/client.rb",
    "lib/commands.rb",
    "lib/credentials.rb",
    "lib/ec2_client_wrapper.rb",
    "lib/elastic-mapreduce-cli.rb",
    "lib/json.rb",
    "lib/json/lexer.rb",
    "lib/json/objects.rb",
    "lib/net/http/connection_pool.rb",
    "lib/net/http/connection_pool/connection.rb",
    "lib/net/http/connection_pool/session.rb",
    "lib/run_tests.rb",
    "lib/simple_executor.rb",
    "lib/simple_logger.rb",
    "lib/uuidtools.rb",
    "lib/uuidtools/version.rb",
    "run_tests.rb",
    "samples/freebase/code/freebase_jobflow.json",
    "samples/similarity/lastfm_jobflow.json",
    "samples/wordSplitter.py",
    "tests/commands_test.rb",
    "tests/credentials.json",
    "tests/example.json",
    "update.sh"
  ]
  s.homepage = "http://github.com/hapyrus/elastic-mapreduce"
  s.licenses = ["Apache License"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Amazon's commandline client for EMR (Elastic Map-Reduce) invocation (Unofficial Gem and Ruby 1.9 Version)"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.1"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.1"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.1"])
  end
end

